apiVersion: v1
kind: Namespace
metadata:
  name: dev-ns
  labels:
    environment: dev
    team: devops
  annotations:
    description: "Namespace for development environment and devops team applications."

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: dev-ns
spec:
  containers:
  - name: nginx-cont
    image: nginx:latest
    ports:
    - containerPort: 80
