apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: my-3tier-app
data:
  # Flask application settings
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "5000"
  # Database connection details (host and port)
  # The full DATABASE_URL will be constructed using Secret for user/pass
  DB_HOST: database-service
  DB_PORT: "5432" # Default PostgreSQL port
