apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: my-3tier-app
type: Opaque
data:
  # PostgreSQL Database Credentials
  POSTGRES_USER: bXlzZWNyZXR1c2Vy
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==
  POSTGRES_DB: bXlkYXRhYmFzZQ==

  # Flask Application Secret Key (IMPORTANT: Generate a strong, random one for production!)
  FLASK_SECRET_KEY: YV9zZWN1cmVfcmFuZG9tX3N0cmluZ19mb3JfcHJvZHVjdGlvbg==

  # Default User Passwords for init_db.py (IMPORTANT: Change these for production!)
  DEFAULT_ADMIN_PASSWORD: YWRtaW5wYXNz
  DEFAULT_INSTRUCTOR_PASSWORD: aW5zdHJ1Y3RvcnBhc3M=

